In [1]:
from ultralytics import YOLO

In [2]:
# Load a model
model = YOLO("yolov8s.pt")  # load a pretrained model (recommended for training)

In [3]:
# Use the model
results = model.predict("https://ultralytics.com/images/bus.jpg")  # predict on an image


Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
image 1/1 C:\Users\rayan\OneDrive\Bureau\HackProject\CellsAI\Env\VisionAi\bus.jpg: 640x480 4 persons, 1 bus, 45.8ms
Speed: 4.0ms preprocess, 45.8ms inference, 12.5ms postprocess per image at shape (1, 3, 640, 480)


In [18]:
import os
os.listdir('deadcells.v1i.yolov8/test/images')

['frame15488_jpg.rf.c14a737ee8d305e0e3adaf53ae19c2d4.jpg',
 'frame21157_jpg.rf.6864c7608028bd66c3983730cb2a78e1.jpg',
 'frame37808_jpg.rf.c122559789d43046b81986784b70f332.jpg',
 'frame4780_jpg.rf.88bc204614befc326caf9a9334318b0e.jpg',
 'frame7660_jpg.rf.6821679576d6f5e7b51dc468384d1a47.jpg',
 'frame7840_jpg.rf.6fc019a7ae2f7fe0caf2ed5bd6a7c0e3.jpg']

In [39]:
from matplotlib import image 
from matplotlib import pyplot as plt 
from PIL import Image, ImageDraw

In [42]:
#=-------------- Testing of the Ai ---------------#
game_model = YOLO("best.pt")
results = game_model('deadcells.v1i.yolov8/test/images/frame15488_jpg.rf.c14a737ee8d305e0e3adaf53ae19c2d4.jpg')
boxes = results[0].boxes
for box in boxes:
    print(box.xyxy)

for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    draw = ImageDraw.Draw(im) 
    draw.line((400.0099,  52.1656, 447.8310, 160.8165), fill=200)
    im.show()
    # im.show()  # show image
    # im.save('results.jpg')
    
# # to read the image stored in the working directory 
# data = image.imread('results.jpg') 
  
# # to draw a point on co-ordinate (200,300) 
# plt.plot(326.1376, 267.5645, marker='v', color="white") 
# plt.imshow(data) 
# plt.show() 



image 1/1 C:\Users\rayan\OneDrive\Bureau\HackProject\CellsAI\Env\VisionAi\deadcells.v1i.yolov8\test\images\frame15488_jpg.rf.c14a737ee8d305e0e3adaf53ae19c2d4.jpg: 640x640 1 agents, 1 enemy_archer, 1 enemy_purple_shield, 187.3ms
Speed: 3.0ms preprocess, 187.3ms inference, 2.4ms postprocess per image at shape (1, 3, 640, 640)


tensor([[172.7727, 275.6490, 207.9804, 375.4407]], device='cuda:0')
tensor([[326.1376, 267.5645, 361.3703, 377.1994]], device='cuda:0')
tensor([[400.0099,  52.1656, 447.8310, 160.8165]], device='cuda:0')


In [ ]:
from ultralytics import YOLO
#--------------- Training starts Here --------------------#
model_small = YOLO("yolov8s.pt")

path_to_data = 'deadcells.v3i.yolov8/data.yaml'

model_small.train(data=path_to_data, epochs=50)  # train the model

Ultralytics YOLOv8.0.206  Python-3.9.18 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
engine\trainer: task=detect, mode=train, model=yolov8s.pt, data=deadcells.v3i.yolov8/data.yaml, epochs=50, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train14, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_

In [ ]:
#new additon
def get_coordinate(coord1, coord2):
    x1, y1 = coord1
    x2, y2 = coord2
    
    # Calculate the middle point.
    coordinate = ((x1 + x2) / 2, (y1 + y2) / 2)

    # Return the coordinate.
    return coordinate

# Example usage:
coordinate = get_coordinate((400.0099, 52.1656), (447.8310, 160.8165))
print("Coordinate:", coordinate)

# You can also call the function directly

get_coordinate((400.0099, 52.1656),(447.8310, 160.8165))